### ISSUE TITLE
Submitting Assignment 2

### ISSUE THREAD

**Issue by adriana-lh** [VIS-2129-F2020/alassoharrier-vis#2]
Hello, 

Assignment 2 has been uploaded and is ready for grading. It can be viewed at:

https://vis-2129-f2020.github.io/alassoharrier-vis/Vis-Assignment-2

**Comment by bauranov** [comment]
Good work on creating your own data!

- At the beginning of a code chunk add {r, message=FALSE, warning=FALSE} to suppress all messages and warnings in HTML. When you knit your file, go through the HTML and see if some code chunks are displaying the text you don't want (such as the part where you plot the choropleth map). If there is such text, remove it with the code I mentioned above.
- Very interesting decision to use only four sizes of circles in the last plot. Glad to see you're thinking about these issues. 

Keep up the good work, I'm looking forward to seeing what you do next.
